<?php


namespace Raphaelrosello\Blog\Block\Post;


use Magento\Framework\DataObject\IdentityInterface;
use Magento\Framework\View\Element\Template;
use Raphaelrosello\Blog\Api\Data\PostInterface;
use Raphaelrosello\Blog\Api\PostRepositoryInterface;
use Raphaelrosello\Blog\Model\Post;

class View extends Template implements IdentityInterface
{
    /**
     * @var PostRepositoryInterface
     */
    protected $postRepository;

    /**
     * @var PostInterface
     */
    protected $post;

    public function __construct(
        Template\Context $context,
        PostRepositoryInterface $postRepository,
        array $data = []
    )
    {
        $this->postRepository = $postRepository;
        parent::__construct($context, $data);
    }

    protected function _construct()
    {
        $post_id = $this->getRequest()->getParam('post_id');
        if($post_id) {
            $post = $this->postRepository->getById($post_id);
            $this->post = $post;

        }
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function getPost()
    {
        return $this->post;
    }

    public function getIdentities()
    {
        return [\Raphaelrosello\Blog\Model\Post::CACHE_TAG . '_' . $this->post->getPostId()];
    }


}