<?php
/** @var $block \Rrosello\Blog\Block\Category\CategoryList */ ?>

<?php /** @var $category \Rrosello\Blog\Api\Data\CategoryInterface */ ?>

<div class="featured-post-sidebar">
    <div class="featured-post-sidebar-title">
        <h3><strong><?php echo $block->escapeHtml(__('Categories')) ?></strong></h3>
    </div>

    <div class="sidebar-category-list">
        <?php foreach ($block->getCategories() as $category): ?>
            <p><a href="#"><?php echo $category->getName() ?></a></p>
        <?php endforeach; ?>
    </div>
</div>
