<?php
/** @var $block \Rrosello\Blog\Block\Post\PostList */ ?>
<?php $helper = $block->getHelperData() ?>

<div class="blog-post-item">
    <?php /** @var $post \Rrosello\Blog\Api\Data\PostInterface */ ?>
    <?php foreach ($block->getPosts() as $post): ?>
        <div class="blog-post-item-image">
            <a href="<?php echo $post->getUrlKey(); ?>">
                <img src="<?php echo $block->getMediaUrl().$post->getImage(); ?>" />
            </a>
        </div>
        <div class="blog-post-item-data">
            <p><a href="#">Category</a></p>
            <h3 class="blog-post-item-title">
                <strong><a href="<?php echo $post->getUrlKey(); ?>"><?php echo $post->getTitle() ?></a></strong>
            </h3>
            <div>
                <p><?php echo $helper->timeElapsed($post->getCreatedAt()) ?></p>
            </div>
        </div>
        <hr>
    <?php endforeach; ?>
</div>
<div class="pagination">
    <button type="button">Older Post</button>
    <button type="button">Newer Post</button>
</div>