<?php
/** @var $block \Raphaelrosello\Blog\Block\Post\PostList */ ?>

<ul class="blog-post-list">
    <?php /** @var $post \Raphaelrosello\Blog\Api\Data\PostInterface */ ?>
    <?php foreach ($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="<?php echo $post->getUrlKey(); ?>"><?php echo $post->getTitle() ?></a>
            </h3>

            <div class="blog-post-item-content">
                <?php echo $post->getContent(); ?>
            </div>

            <div class="blog-post-item-meta">
                <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt() ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>