<?php
/** @var $block \Rrosello\Blog\Block\Post\PostList */ ?>

<ul class="blog-post-list">
    <?php /** @var $post \Rrosello\Blog\Api\Data\PostInterface */ ?>
    <?php foreach ($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <img class="img-thumbnail" style="width: 100px;" src="<?php echo $block->getMediaUrl().'/'.$post->getImage(); ?>" />
                    </div>
                    <div class="col-sm-8">
                        <h3 class="blog-post-item-title">
                            <a href="<?php echo $post->getUrlKey(); ?>"><?php echo $post->getTitle() ?></a>
                        </h3>
                        <div class="blog-post-item-meta">
                            <?php echo $post->getCreatedAt() ?>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
</ul>